### ISSUE TITLE
"significant diffrent rules can influence / create errors to each other" or "NAC Problem in Democles"

### ISSUE THREAD

**Issue by SaschaEdwinZander** [eMoflon/emoflon-tool#105] opened 2016-09-30 15:26 UTC
## First to get an example:

- Checkout the branch [szander-Issue85-EClassViz](https://github.com/eMoflon/emoflon-tool/tree/szander-Issue85-EClassViz)
- download [test.zip](https://github.com/eMoflon/emoflon-tool/files/503174/test.zip) and unzip it to org.moflon.visualization.dot.ecore.eclassviz/instances/
- start EclassvizTrafo
- look at the bwd.trg.xmi
- To see the error: remove "#abstract" from any TGGRule which ends with "EReferenceRule.tgg" (becareful rules with the ending "EReferenceAbstractRule.tgg" must be abstract!)
- build
- start EclassvizTrafo
- again look at the bwd.trg.xmi

## The Error:
After "activating" the EReference rules the EAttributes can't be translated by the TGG although the EReferences rules have nothing to do with the EAttribute rule.

I have found out that in the EAttribute Rule (named "AddAttributesToClassRule") the isAppropriate_BWD_EMoflonEdge_XXXX() method the generated Activity "test core match and DECs" is changed.

before activating the EReferenceRules
![before](https://cloud.githubusercontent.com/assets/9741282/18996392/7a06143a-8730-11e6-9b5f-100561334c5c.png)

after activating the EReferenceRules
![after](https://cloud.githubusercontent.com/assets/9741282/18996433/9e063cd4-8730-11e6-88c8-e4cef426e94b.png)

I guess there is a problem with NACs because in the generated code the Activity is trying to match for `eClass.equals(eAttribute.getEType())` which is absolutly wrong. (In the real code code it is not this Expression, it's more complex but if you try to solve it to an easier expression it is this!)

**Comment by SaschaEdwinZander** [comment] 2016-09-30 16:03
This is the relevant code from the generator

```
public EObjectContainer isAppropriate_BWD_EMoflonEdge_XXXX(EMoflonEdge _edge_eContainingClass) {
		...
    // ForEach test core match and DECs
    for (Object[] result2_black : AddAttributesToClassRuleImpl.crypticNamePattern1(_edge_eContainingClass)) {
			EAttribute eAttribute = (EAttribute) result2_black[0];
			EClass eClass = (EClass) result2_black[1];
								...
    }
}
```

```
public static final Iterable<Object[]> crypticNamePattern1(EMoflonEdge _edge_eContainingClass) {
    ...
        if (crypticNamePattern2(eAttribute, eClass) == null) {
            .... //important stuff for the rule!
	}
    ...
}
```

```
public static final Object[] crypticNamePattern2(
	EAttribute eAttribute, EClass eClass) {
	EClassifier __DEC_eAttribute_eType_168904 = eAttribute.getEType();
	if (__DEC_eAttribute_eType_168904 != null) {
		if (!eClass.equals(__DEC_eAttribute_eType_168904)) {
			return new Object[] { eAttribute, eClass };
		}
	}
	return null;
}
```

This is the relevant part of the translation from generator. If the eType of the eAttribute is diffrent from the eClass `crypticNamePattern2()` is not null and so the "important stuff" is not going to work and so on.
I think anywhere are too many negations.

**Comment by anthonyanjorin** [comment] 2016-09-30 16:31
This is not a bug.  Our algorithm generates NACs to ensure that there are no edges that can no longer be translated when applying a certain rule.  So the version of the rule with NACs basically says:  you have no rule translating the edge "eType" of the attribute, so don't apply this rule if this edge is present.

As it is a bit stressful to write up ignore rules for all such edges, we try to ignore as much as possible automatically.  The way we do this is, however, conservative:

- if no rule in the entire tgg ever translates a certain edge, then we do not block applications (as it can't be translated anyway)

But once you add a rule that potentially has the chance to translate this edge, then we activate the NAC generation again.

I assume this is what is happening here.  To solve the problem, just add an ignore rule that explicitly ignores the type edge of attributes in exactly this situation (green edge between black nodes).

**Comment by anthonyanjorin** [comment] 2016-10-04 07:21
@SaschaEdwinZander Can we close this now?

**Closed** 2016-10-05 09:54 UTC
Labels: bug, eMoflon-Democles, eMoflon-TGG, high-priority
